name: cat_random_fact
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  injectable: ^2.1.0
  json_annotation: ^4.7.0
  flutter_bloc: ^8.1.2
  dio: ^4.0.6
  retrofit: '>=3.0.0 <4.0.0'
  get_it: ^7.2.0
  go_router: ^6.0.1
  flutter_pretty_dio_logger: ^2.0.3
  either_dart: ^0.3.0
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.3
  json_serializable: ^6.5.4
  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner: '>2.3.0 <4.0.0' 
  hive_generator: ^2.0.0


flutter:
  uses-material-design: true

        
    
    
                                  #
    